<?php

namespace app\widgets\sidebar;


use app\models\Article;
use app\models\ArticleTag;
use app\models\Category;
use app\models\Comment;
use app\models\TagBlackList;
use app\models\UserBlackList;
use Yii;
use yii\base\Widget;

class Sidebar extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
//        $popular = $this->getPopular();
//        $latest = Article::find()->where(['status' => 1])->orderBy('date desc')->limit(4)->all();
        $popular = $this->getPopular();
        $latest = $this->getAll('latest');
        $category = Category::find()->all();

        return $this->render('sidebar', compact('popular', 'latest', 'category'));
    }

    private function getAll($category)
    {
        $query = $this->getQuery($category);
        return $query->all();
    }

    private function getQuery($category)
    {
        $blocked_id = $this->getBlockedId();
        if ($category == 'popular') {
//            $query = $this->popularArticles();
        } elseif ($category == 'latest') {
            $query = $this->latestArticles();
        }
        $this->getOutBlockedArticle($query, $blocked_id);
        return $query;
    }

    private function getBlockedId()
    {
        if (!Yii::$app->user->isGuest) {
            $user_id = Yii::$app->user->id;
            $blockedUsersId = $this->getBlockedUsersId($user_id);
            $blockedTagsId = $this->getBlockedTagsId($user_id);
            if ($blockedUsersId & $blockedTagsId) {
                $array_merge = array_merge($blockedUsersId, $blockedTagsId);
                $result = array_unique($array_merge);
                return $result;
            } elseif ($blockedUsersId) {
                $result = $blockedUsersId;
                return $result;
            } elseif ($blockedTagsId) {
                $result = $blockedTagsId;
                return $result;
            }
        }
    }

    private function getBlockedTagsId($user_id)
    {
        $blockedId = TagBlackList::find()->where(['user_id' => $user_id])->all();
        if ($blockedId) {
            foreach ($blockedId as $item) {
                $id = $item->black_list_tag;
                $articleTags = ArticleTag::find()->where(['tag_id' => $id])->all();
                foreach ($articleTags as $value) {
                    $blockedTagsId[] = $value->article_id;
                }
            }
            $result = array_unique($blockedTagsId);
            return $result;
        }
    }

    private function getBlockedUsersId($user_id)
    {
        $blockedId = UserBlackList::find()->where(['user_id' => $user_id])->all();
        if ($blockedId) {
            foreach ($blockedId as $item) {
                $id = $item->black_list_user;
                $articleUser = Article::find()->where(['user_id' => $id])->all();
                foreach ($articleUser as $value) {
                    $blockedUsersId[] = $value->id;
                }
            }
            $result = array_unique($blockedUsersId);
            return $result;
        }
    }

    private function getOutBlockedArticle($query, $blocked_id)
    {
        if ($blocked_id) {
            foreach ($blocked_id as $item) {
                $query->andWhere(['!=', 'id', $item]);
            }
        }
    }

    private function latestArticles()
    {
        $query = Article::find()->where(['status' => 1])->orderBy('date desc')->limit(4);
        return $query;
    }





    private function getPopular()
    {
        $date = $this->dateAgo();
        $latest_article_id_array = $this->getLatestArticle($date);
        if ($latest_article_id_array) {
            $the_most_popular_articles = $this->getPopularArticle($latest_article_id_array);
            if ($the_most_popular_articles) {
                foreach ($the_most_popular_articles as $article) {
                    $popular_arr[] = Article::find()->where(['status' => 1, 'id' => $article])->all();
                }
                foreach ($popular_arr as $k => $item) {
                    foreach ($item as $v => $value) {
                        $popular[] = $value;
                    }
                } return $popular;
            } else return $popular = [];
        } else return $popular = [];
    }

    private function dateAgo()
    {
        $oneMonthAgo = time() - 60*60*24*7;
        $date = date('Y-m-d', $oneMonthAgo);
        return $date;
    }

    private function getLatestArticle($date)
    {
        $query = "SELECT id FROM article WHERE date > '$date' AND status = 1";
        $latest_article_id = Article::findBySql($query)->asArray()->all();
        if ($latest_article_id) {
            $latest_article_id_array = $this->getReadableArray($latest_article_id);
            return $latest_article_id_array;
        }
    }

    private function getPopularArticle($article_array)
    {
        $article_comment_array = $this->getArticleCommentArray($article_array);
        if ($article_comment_array) {
            $the_most_popular_articles = $this->theMostPopularArticles($article_comment_array);
            return $the_most_popular_articles;
        }
    }

    private function getArticleCommentArray($article_array)
    {
        $keys = [];
        $value = [];
        foreach ($article_array as $article_id) {
            $count_comment_id = Comment::find()->where(['article_id' => $article_id])->count();
            if ($count_comment_id) {
                $value[] = $count_comment_id;
                $keys[] = $article_id;
            }
        }
        $article_comment_array = array_combine($keys, $value);
        return $article_comment_array;
    }

    private function theMostPopularArticles($array)
    {
        arsort($array);
        $array = array_slice($array, 0, 3, true);
        foreach ($array as $k => $item) {
            $id_array[] = $k;
        }
        return $id_array;
    }

    private function getReadableArray($uselessArray)
    {
        foreach ($uselessArray as $k => $item) {
            foreach ($item as $v => $value) {
                $array[] = $value;
            }
        }
        return $array;
    }
}